/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserFavoriteRestaurantCreateNestedManyWithoutUsersInput } from "./UserFavoriteRestaurantCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { UserInteractionCreateNestedManyWithoutUsersInput } from "./UserInteractionCreateNestedManyWithoutUsersInput";
import { UserSearchHistoryCreateNestedManyWithoutUsersInput } from "./UserSearchHistoryCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserFavoriteRestaurantCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserFavoriteRestaurantCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserFavoriteRestaurantCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userFavoriteRestaurants?: UserFavoriteRestaurantCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserInteractionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserInteractionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserInteractionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userInteractions?: UserInteractionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => UserSearchHistoryCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserSearchHistoryCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserSearchHistoryCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userSearchHistories?: UserSearchHistoryCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
