/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserFavoriteRestaurantService } from "../userFavoriteRestaurant.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserFavoriteRestaurantCreateInput } from "./UserFavoriteRestaurantCreateInput";
import { UserFavoriteRestaurant } from "./UserFavoriteRestaurant";
import { UserFavoriteRestaurantFindManyArgs } from "./UserFavoriteRestaurantFindManyArgs";
import { UserFavoriteRestaurantWhereUniqueInput } from "./UserFavoriteRestaurantWhereUniqueInput";
import { UserFavoriteRestaurantUpdateInput } from "./UserFavoriteRestaurantUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserFavoriteRestaurantControllerBase {
  constructor(
    protected readonly service: UserFavoriteRestaurantService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserFavoriteRestaurant })
  @nestAccessControl.UseRoles({
    resource: "UserFavoriteRestaurant",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserFavoriteRestaurant(
    @common.Body() data: UserFavoriteRestaurantCreateInput
  ): Promise<UserFavoriteRestaurant> {
    return await this.service.createUserFavoriteRestaurant({
      data: {
        ...data,

        restaurant: data.restaurant
          ? {
              connect: data.restaurant,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        createDate: true,
        id: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updateDate: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserFavoriteRestaurant] })
  @ApiNestedQuery(UserFavoriteRestaurantFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserFavoriteRestaurant",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userFavoriteRestaurants(
    @common.Req() request: Request
  ): Promise<UserFavoriteRestaurant[]> {
    const args = plainToClass(
      UserFavoriteRestaurantFindManyArgs,
      request.query
    );
    return this.service.userFavoriteRestaurants({
      ...args,
      select: {
        createdAt: true,
        createDate: true,
        id: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updateDate: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserFavoriteRestaurant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserFavoriteRestaurant",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userFavoriteRestaurant(
    @common.Param() params: UserFavoriteRestaurantWhereUniqueInput
  ): Promise<UserFavoriteRestaurant | null> {
    const result = await this.service.userFavoriteRestaurant({
      where: params,
      select: {
        createdAt: true,
        createDate: true,
        id: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        updateDate: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserFavoriteRestaurant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserFavoriteRestaurant",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserFavoriteRestaurant(
    @common.Param() params: UserFavoriteRestaurantWhereUniqueInput,
    @common.Body() data: UserFavoriteRestaurantUpdateInput
  ): Promise<UserFavoriteRestaurant | null> {
    try {
      return await this.service.updateUserFavoriteRestaurant({
        where: params,
        data: {
          ...data,

          restaurant: data.restaurant
            ? {
                connect: data.restaurant,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          createDate: true,
          id: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updateDate: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserFavoriteRestaurant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserFavoriteRestaurant",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserFavoriteRestaurant(
    @common.Param() params: UserFavoriteRestaurantWhereUniqueInput
  ): Promise<UserFavoriteRestaurant | null> {
    try {
      return await this.service.deleteUserFavoriteRestaurant({
        where: params,
        select: {
          createdAt: true,
          createDate: true,
          id: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          updateDate: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
