/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserInteractionService } from "../userInteraction.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserInteractionCreateInput } from "./UserInteractionCreateInput";
import { UserInteraction } from "./UserInteraction";
import { UserInteractionFindManyArgs } from "./UserInteractionFindManyArgs";
import { UserInteractionWhereUniqueInput } from "./UserInteractionWhereUniqueInput";
import { UserInteractionUpdateInput } from "./UserInteractionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserInteractionControllerBase {
  constructor(
    protected readonly service: UserInteractionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserInteraction })
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserInteraction(
    @common.Body() data: UserInteractionCreateInput
  ): Promise<UserInteraction> {
    return await this.service.createUserInteraction({
      data: {
        ...data,

        restaurant: data.restaurant
          ? {
              connect: data.restaurant,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        deviceType: true,
        id: true,
        interactionTimestamp: true,
        interactionType: true,
        ipAddress: true,
        latitude: true,
        longitude: true,
        offerId: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserInteraction] })
  @ApiNestedQuery(UserInteractionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userInteractions(
    @common.Req() request: Request
  ): Promise<UserInteraction[]> {
    const args = plainToClass(UserInteractionFindManyArgs, request.query);
    return this.service.userInteractions({
      ...args,
      select: {
        createdAt: true,
        deviceType: true,
        id: true,
        interactionTimestamp: true,
        interactionType: true,
        ipAddress: true,
        latitude: true,
        longitude: true,
        offerId: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserInteraction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userInteraction(
    @common.Param() params: UserInteractionWhereUniqueInput
  ): Promise<UserInteraction | null> {
    const result = await this.service.userInteraction({
      where: params,
      select: {
        createdAt: true,
        deviceType: true,
        id: true,
        interactionTimestamp: true,
        interactionType: true,
        ipAddress: true,
        latitude: true,
        longitude: true,
        offerId: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserInteraction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserInteraction(
    @common.Param() params: UserInteractionWhereUniqueInput,
    @common.Body() data: UserInteractionUpdateInput
  ): Promise<UserInteraction | null> {
    try {
      return await this.service.updateUserInteraction({
        where: params,
        data: {
          ...data,

          restaurant: data.restaurant
            ? {
                connect: data.restaurant,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          deviceType: true,
          id: true,
          interactionTimestamp: true,
          interactionType: true,
          ipAddress: true,
          latitude: true,
          longitude: true,
          offerId: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserInteraction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserInteraction(
    @common.Param() params: UserInteractionWhereUniqueInput
  ): Promise<UserInteraction | null> {
    try {
      return await this.service.deleteUserInteraction({
        where: params,
        select: {
          createdAt: true,
          deviceType: true,
          id: true,
          interactionTimestamp: true,
          interactionType: true,
          ipAddress: true,
          latitude: true,
          longitude: true,
          offerId: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
