/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserInteraction } from "./UserInteraction";
import { UserInteractionCountArgs } from "./UserInteractionCountArgs";
import { UserInteractionFindManyArgs } from "./UserInteractionFindManyArgs";
import { UserInteractionFindUniqueArgs } from "./UserInteractionFindUniqueArgs";
import { CreateUserInteractionArgs } from "./CreateUserInteractionArgs";
import { UpdateUserInteractionArgs } from "./UpdateUserInteractionArgs";
import { DeleteUserInteractionArgs } from "./DeleteUserInteractionArgs";
import { Restaurant } from "../../restaurant/base/Restaurant";
import { User } from "../../user/base/User";
import { UserInteractionService } from "../userInteraction.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserInteraction)
export class UserInteractionResolverBase {
  constructor(
    protected readonly service: UserInteractionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "read",
    possession: "any",
  })
  async _userInteractionsMeta(
    @graphql.Args() args: UserInteractionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserInteraction])
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "read",
    possession: "any",
  })
  async userInteractions(
    @graphql.Args() args: UserInteractionFindManyArgs
  ): Promise<UserInteraction[]> {
    return this.service.userInteractions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserInteraction, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "read",
    possession: "own",
  })
  async userInteraction(
    @graphql.Args() args: UserInteractionFindUniqueArgs
  ): Promise<UserInteraction | null> {
    const result = await this.service.userInteraction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserInteraction)
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "create",
    possession: "any",
  })
  async createUserInteraction(
    @graphql.Args() args: CreateUserInteractionArgs
  ): Promise<UserInteraction> {
    return await this.service.createUserInteraction({
      ...args,
      data: {
        ...args.data,

        restaurant: args.data.restaurant
          ? {
              connect: args.data.restaurant,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserInteraction)
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "update",
    possession: "any",
  })
  async updateUserInteraction(
    @graphql.Args() args: UpdateUserInteractionArgs
  ): Promise<UserInteraction | null> {
    try {
      return await this.service.updateUserInteraction({
        ...args,
        data: {
          ...args.data,

          restaurant: args.data.restaurant
            ? {
                connect: args.data.restaurant,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserInteraction)
  @nestAccessControl.UseRoles({
    resource: "UserInteraction",
    action: "delete",
    possession: "any",
  })
  async deleteUserInteraction(
    @graphql.Args() args: DeleteUserInteractionArgs
  ): Promise<UserInteraction | null> {
    try {
      return await this.service.deleteUserInteraction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Restaurant, {
    nullable: true,
    name: "restaurant",
  })
  @nestAccessControl.UseRoles({
    resource: "Restaurant",
    action: "read",
    possession: "any",
  })
  async getRestaurant(
    @graphql.Parent() parent: UserInteraction
  ): Promise<Restaurant | null> {
    const result = await this.service.getRestaurant(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: UserInteraction
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
