/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RestaurantPhotoService } from "../restaurantPhoto.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RestaurantPhotoCreateInput } from "./RestaurantPhotoCreateInput";
import { RestaurantPhoto } from "./RestaurantPhoto";
import { RestaurantPhotoFindManyArgs } from "./RestaurantPhotoFindManyArgs";
import { RestaurantPhotoWhereUniqueInput } from "./RestaurantPhotoWhereUniqueInput";
import { RestaurantPhotoUpdateInput } from "./RestaurantPhotoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RestaurantPhotoControllerBase {
  constructor(
    protected readonly service: RestaurantPhotoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RestaurantPhoto })
  @nestAccessControl.UseRoles({
    resource: "RestaurantPhoto",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRestaurantPhoto(
    @common.Body() data: RestaurantPhotoCreateInput
  ): Promise<RestaurantPhoto> {
    return await this.service.createRestaurantPhoto({
      data: {
        ...data,

        restaurant: data.restaurant
          ? {
              connect: data.restaurant,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        photoUrl: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RestaurantPhoto] })
  @ApiNestedQuery(RestaurantPhotoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RestaurantPhoto",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async restaurantPhotos(
    @common.Req() request: Request
  ): Promise<RestaurantPhoto[]> {
    const args = plainToClass(RestaurantPhotoFindManyArgs, request.query);
    return this.service.restaurantPhotos({
      ...args,
      select: {
        createdAt: true,
        id: true,
        photoUrl: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RestaurantPhoto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RestaurantPhoto",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async restaurantPhoto(
    @common.Param() params: RestaurantPhotoWhereUniqueInput
  ): Promise<RestaurantPhoto | null> {
    const result = await this.service.restaurantPhoto({
      where: params,
      select: {
        createdAt: true,
        id: true,
        photoUrl: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RestaurantPhoto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RestaurantPhoto",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRestaurantPhoto(
    @common.Param() params: RestaurantPhotoWhereUniqueInput,
    @common.Body() data: RestaurantPhotoUpdateInput
  ): Promise<RestaurantPhoto | null> {
    try {
      return await this.service.updateRestaurantPhoto({
        where: params,
        data: {
          ...data,

          restaurant: data.restaurant
            ? {
                connect: data.restaurant,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          photoUrl: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RestaurantPhoto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RestaurantPhoto",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRestaurantPhoto(
    @common.Param() params: RestaurantPhotoWhereUniqueInput
  ): Promise<RestaurantPhoto | null> {
    try {
      return await this.service.deleteRestaurantPhoto({
        where: params,
        select: {
          createdAt: true,
          id: true,
          photoUrl: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
