/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RestaurantWorkingHourService } from "../restaurantWorkingHour.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RestaurantWorkingHourCreateInput } from "./RestaurantWorkingHourCreateInput";
import { RestaurantWorkingHour } from "./RestaurantWorkingHour";
import { RestaurantWorkingHourFindManyArgs } from "./RestaurantWorkingHourFindManyArgs";
import { RestaurantWorkingHourWhereUniqueInput } from "./RestaurantWorkingHourWhereUniqueInput";
import { RestaurantWorkingHourUpdateInput } from "./RestaurantWorkingHourUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RestaurantWorkingHourControllerBase {
  constructor(
    protected readonly service: RestaurantWorkingHourService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RestaurantWorkingHour })
  @nestAccessControl.UseRoles({
    resource: "RestaurantWorkingHour",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRestaurantWorkingHour(
    @common.Body() data: RestaurantWorkingHourCreateInput
  ): Promise<RestaurantWorkingHour> {
    return await this.service.createRestaurantWorkingHour({
      data: {
        ...data,

        restaurant: data.restaurant
          ? {
              connect: data.restaurant,
            }
          : undefined,
      },
      select: {
        closingTime: true,
        createdAt: true,
        dayOfWeek: true,
        id: true,
        isClosed: true,
        openingTime: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RestaurantWorkingHour] })
  @ApiNestedQuery(RestaurantWorkingHourFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RestaurantWorkingHour",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async restaurantWorkingHours(
    @common.Req() request: Request
  ): Promise<RestaurantWorkingHour[]> {
    const args = plainToClass(RestaurantWorkingHourFindManyArgs, request.query);
    return this.service.restaurantWorkingHours({
      ...args,
      select: {
        closingTime: true,
        createdAt: true,
        dayOfWeek: true,
        id: true,
        isClosed: true,
        openingTime: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RestaurantWorkingHour })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RestaurantWorkingHour",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async restaurantWorkingHour(
    @common.Param() params: RestaurantWorkingHourWhereUniqueInput
  ): Promise<RestaurantWorkingHour | null> {
    const result = await this.service.restaurantWorkingHour({
      where: params,
      select: {
        closingTime: true,
        createdAt: true,
        dayOfWeek: true,
        id: true,
        isClosed: true,
        openingTime: true,

        restaurant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RestaurantWorkingHour })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RestaurantWorkingHour",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRestaurantWorkingHour(
    @common.Param() params: RestaurantWorkingHourWhereUniqueInput,
    @common.Body() data: RestaurantWorkingHourUpdateInput
  ): Promise<RestaurantWorkingHour | null> {
    try {
      return await this.service.updateRestaurantWorkingHour({
        where: params,
        data: {
          ...data,

          restaurant: data.restaurant
            ? {
                connect: data.restaurant,
              }
            : undefined,
        },
        select: {
          closingTime: true,
          createdAt: true,
          dayOfWeek: true,
          id: true,
          isClosed: true,
          openingTime: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RestaurantWorkingHour })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RestaurantWorkingHour",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRestaurantWorkingHour(
    @common.Param() params: RestaurantWorkingHourWhereUniqueInput
  ): Promise<RestaurantWorkingHour | null> {
    try {
      return await this.service.deleteRestaurantWorkingHour({
        where: params,
        select: {
          closingTime: true,
          createdAt: true,
          dayOfWeek: true,
          id: true,
          isClosed: true,
          openingTime: true,

          restaurant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
