export type AppUserCreateInput = {
  accountStatus?: "Option1" | null;
  address?: string | null;
  authId?: string | null;
  country?: string | null;
  dateOfBirth?: Date | null;
  email?: string | null;
  gender?: "Option1" | null;
  languagePreference?: string | null;
  lastLogin?: Date | null;
  latitude?: number | null;
  longitude?: number | null;
  name?: string | null;
  password?: string | null;
  phoneNumber?: string | null;
  profilePictureUrl?: string | null;
  timezone?: string | null;
  userType?: "Option1" | null;
  verificationStatus?: "Option1" | null;
};
